### teste

GET  http://localhost:5190/api/carros

###
GET  http://localhost:5190/api/carros/1


###Cadastrar carro

POST http://localhost:5190/api/carros
Content-Type: application/json

{
    "Name": "Fusca"
}
###remove carro pelo id
DELETE http://localhost:5190/api/carros


###ATUALIZA DADOS CARRO
PUT http://localhost:5190/api/carros
Content-Type: application/json

{
    "Name": "Fusca"
}